version: "3"
services:
  web:
    container_name: yjm_assistive_tech_manager_web
    build:
      context: .
      dockerfile: dockerization/web/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8083:80

  db:
    container_name: yjm_assistive_tech_manager_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: assistive_tech_manager
      MYSQL_USER: admin_testing_docker
      MYSQL_PASSWORD: admin_testing_docker
    ports:
      - 3318:3306

  phpmyadmin:
    container_name: yjm_assistive_tech_manager_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8093:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin